version: '3.9'

services:
  hanyu-postgresql:
    image: postgres:13.1
    container_name: hanyu-postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=hanyu-app
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - hanyu-network
networks:
  hanyu-network:
    driver: bridge

volumes:
  postgres: